// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: VOA

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void button1_add_count(lv_event_t * e);
void button3_dec_count(lv_event_t * e);
void button4_add_count(lv_event_t * e);
void button5_dec_count(lv_event_t * e);
void button6_add_count(lv_event_t * e);
void button7_dec_count(lv_event_t * e);
void button8_add_count(lv_event_t * e);
void button9_dec_count(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
